# Generated by Django 4.2.19 on 2025-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='years_of_experience_required',
            field=models.IntegerField(default=0),
        ),
    ]
